root: true
parser: 'vue-eslint-parser'
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 'latest'
  ecmaFeatures:
    jsx: true
  sourceType: 'module'
extends: ['standard', 'plugin:vue/vue3-recommended', 'prettier']
plugins: ['import']
rules:
  vue/no-unused-vars: 'error' # https://eslint.vuejs.org/rules/ 查看具体规则
  vue/no-unused-components: 'error'
  vue/multi-word-component-names: 0 # 组件名必须多个单词 0: 关闭, 等价于off
  vue/require-default-prop: off # props 必须定义默认值
  vue/require-prop-types: 0 # props必须定义类型
  no-dupe-class-members: off # ts有校验, 不需要此规则
  no-redeclare: off #禁用eslint默认的禁止重复声明, 因为会误报ts的函数重载
  import/order:
    - 'error'
    - 'groups':
        - 'builtin'
        - 'external'
        - 'internal'
        - 'unknown'
        - 'parent'
        - 'sibling'
        - 'index'
        - 'object'
        - 'type'
